sudo: required
language: node_js
node_js:
  - node
  - 4.4.7
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y cvs xinetd
  - sh specs/fixtures/config.ubuntu.sh
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/d7e22f859cbf45b63ffa
    on_success: always
    on_failure: always
    on_start:   always
