sudo: required
language: node_js
services:
  - docker
node_js:
  - node
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y cvs
  - docker build -t cvs-core .
  - docker run -d -v $PWD/test/fixtures/remote:/var/cvsroot -p 2401:2401 cvs-core
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/198ec30cc47319b28cbb
    on_success: always
    on_failure: always
    on_start:   always
