sudo: required
language: node_js
services:
  - docker
node_js:
  - node
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y cvs
  - docker pull costamauricio/alpine-cvs
  - docker run -d -e CVS_USER=cvsuser -e CVS_PASSWD=cvspass -v $PWD/test/fixtures/remote:/var/cvsroot -p 2401:2401 costamauricio/alpine-cvs
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/198ec30cc47319b28cbb
    on_success: always
    on_failure: always
    on_start:   always
